source 'https://rubygems.org'

#gem 'celluloid'
#gem 'heisencoin', :git => "git://github.com/cointhink/heisencoin.git"

gem 'httparty'
gem 'nn-core' #, :git => "git://github.com/chuckremes/nn-core.git"

